name = "eneRG"
author = "Grey Cat"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6a54e7389591a33261939c088b25874ecfbf14acef8a9cb391395b7d8784f93"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21-1.21.1"]
