#Switch re-rolling cost from experience points to full enchantment levels, making re-rolls considerable more expensive.
#Default Value: false
rerolling_takes_enchantment_levels = true
#Amount of catalyst item taken as a cost for re-rolling enchantments. Set to 0 to disable this kind of cost.
#The default re-roll catalyst is simply lapis lazuli as defined in 'easymagic:enchanting_catalysts'.
#Requires the re-rolling option to be enabled.
#Default Value: 1
#Range: 0 ~ 64
reroll_catalyst_cost = 1
#Amount of experience points (not enchantment levels) taken as a cost for re-rolling enchantments. Set to 0 to disable this kind of cost.
#Requires the re-rolling option to be enabled.
#Default Value: 5
#Range: > 0
reroll_experience_points_cost = 1
